name: Deploy Backend to Render

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Call Render Deploy Hook
        run: |
          curl -X POST https://api.render.com/deploy/srv-xxxxxxxxxxxx?key=xxxxxxxx
